package com.companyservice.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

import java.time.LocalDate;

@Entity //This indicates that the Company class is a JPA (Java Persistence API) entity, which means it will be mapped to a database table.
@Data //This is provided by Lombok library. It automatically generates boilerplate code for getter, setter, toString, reducing the need for manual code.
public class Company {
    @Id // 'companyId' field as the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // companyId field's value will be automatically generated by the 'companydb' database when a new Company object is persisted. The strategy GenerationType.IDENTITY typically relies on auto-increment columns in databases.
    private int companyId;
    private String companyName;
    private String description;
    private String location;
    private String industry;
    private String establishedDate;
    private String contactDetails;
    private String email;
    private String password;
    private String backImage;
    private String profileImage; //These lines declare instance variables to store various attributes of a company such as ... and it will hold data for each company object.
}
